hparams:
  vocab_size: 33
  dim_embedding: 32
  max_seq_len: 6
  hiddens:
    - 64
    - 128
    - 64
  activation: LeakyReLU
  batch_norm: true
  bias: true
  dropout: null
  custom_embedding: null
  freeze_embedding: false
  num_class: 2
