hparams:
  vocab_size: 33
  dim_embedding: 32
  filter_size_list:
    - 1
    - 2
    - 6
    - 8
    - 16
    - 32
    - 64
  filter_num_list: 64
  conv_activation: ReLU
  conv_pooling: max
  hiddens:
    - 128
    - 64
  activation: ReLU
  bias: true
  batch_norm: true
  dropout: null
  custom_embedding: null
  freeze_embedding: false
  num_class: 2
