args:
  project: ProteinVAE
  dataset: template
  model: /home/hew/python/LatentEvolution/framework/config/model/template.yaml
  seed: 42
  tokenization:
    alphabet: ESM-1b
    truncation_seq_length: null
  train_dataloader:
    batch_size: 64
    num_workers: 4
    shuffle: true
    drop_last: true
    pin_memory: true
    persistent_workers: true
  valid_dataloader:
    batch_size: 64
    num_workers: 4
    shuffle: false
    pin_memory: true
    persistent_workers: true
  test_dataloader:
    batch_size: 64
    num_workers: 4
    shuffle: false
    pin_memory: true
    persistent_workers: true
  predict_dataloader:
    batch_size: 64
    num_workers: 4
    shuffle: false
    pin_memory: true
    persistent_workers: true
  trainer:
    max_epochs: 100
    accelerator: auto
    strategy: auto
    devices: auto
    deterministic: false
    benchmark: true
    sync_batchnorm: true
    log_every_n_steps: 1
    check_val_every_n_epoch: 1
    fast_dev_run: false
    num_sanity_val_steps: 2
    enable_model_summary: true
    reload_dataloaders_every_n_epochs: 0
    gradient_clip_val: 1.0
    gradient_clip_algorithm: norm
    enable_checkpointing: true
    accumulate_grad_batches: 1
    val_check_interval: 0.5
  logger:
    save_dir: ./script/task_02_ProteinVAE/
    name: lightning_logs
  progress_bar_callback:
    refresh_rate: 1
    process_position: 0
  ckpt_callback:
    monitor: valid/loss_epoch
    filename: epoch={epoch:02d}, loss={valid/loss_epoch:.3f}, ce={valid/ce_epoch:.3f},
      reg={valid/reg_epoch:.3f}, mse={valid/mse_epoch:.3f}, ddG={valid/ddG_pearsonr_epoch:.3f},
      dS={valid/dS_pearsonr_epoch:.3f}
    auto_insert_metric_name: false
    save_weights_only: true
    mode: min
    save_top_k: 50
    save_last: true
  early_stop_callback:
    monitor: valid/loss_epoch
    min_delta: 0.01
    patience: 200
    mode: min
  swa_callback: null
  xlsx_output_format:
    general_format:
      align: center
      valign: vcenter
    number_format:
      num_format: '#,##0.0000'
      align: center
      valign: vcenter
  nni:
    auto_ml: false
    metric: AUC
    use_best: true
  data:
    dataset: ACE2_variants_2k
    sequence_length: 83
    mini_set_ratio: null
    data_class: Protein
    lazy_load: false
    train_ratio: 0.7
    valid_ratio: 0.1
    test_ratio: 0.2
    split_valid: null
    label: ddG
    max_len: 83
  hparams:
    encoder_transformer:
      num_layers: 4
      embed_dim: 128
      attention_heads: 16
      alphabet: ESM-1b
      token_dropout: false
      embedding_layer: true
      lm_head: false
      return_layer: -1
    encoder_mlp:
      hiddens:
      - 128
      - 64
      - 32
      activation: ReLU
      batch_norm: false
      layer_norm: true
      bias: true
      dropout: 0.05
    decoder_mlp:
      hiddens:
      - 16
      - 64
      - 128
      activation: ReLU
      batch_norm: false
      layer_norm: true
      bias: true
      dropout: 0.05
    decoder_transformer:
      num_layers: 4
      embed_dim: 128
      attention_heads: 16
      alphabet: ESM-1b
      token_dropout: false
      embedding_layer: false
      lm_head: false
      return_layer: -1
    regressor_head:
      hiddens:
      - 1360
      - 256
      - 128
      - 2
      activation: ReLU
      batch_norm: true
      bias: true
      dropout: 0.05
    reparameterization: false
  optimizer:
    name: RAdam
    args:
      lr: 0.0005
      weight_decay: 0
  scheduler:
    name: LinearLR
    args:
      start_factor: 1
      end_factor: 0.01
      total_iters: 12500
    interval: step
    frequency: 1
  loss:
    mse_loss:
      name: MSELoss
      args: {}
    ce_loss:
      name: CrossEntropy
      args: {}
    mmd_loss:
      name: MMDLoss
      args:
        sigma: 20
    ce_weight: 1.0
    mse_weight: 1000.0
    reg_weight: 0.1
  -f: null
  /home/hew/:
    local/share/jupyter/runtime/kernel-c7560856-3669-486d-8444-5fc66bdf7e92:
      json: null
